spring:
  application:
    name: mvp-saude
  profiles:
    active: dev
#    active: test

defaultTenant: tenant1
personal:
  security:
    jwtSecret: aa713c1f-8025-4ce4-bfe8-0a8ea6110eea
    jwtExpirationMs: 360 000 000
    jwtRefreshExpirationMs: 6 000 000
    passwordGenerate: generated
    url-cors: http://localhost:4200

